server:
  port: 8888
spring:
  application:
    name: config-server
  profile:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-config-repo.git
          search-paths: config
          clone-on-start: true
management:
  endpoints:
    web:
      exposure:
        include: health, info

